### ISSUE TITLE
无法预览设为私密的作品-职业攻略

### ISSUE THREAD

**Issue by githubaby** [JX3BOX/jx3box.github.io#2]
![QQ图片20200614213809](https://user-images.githubusercontent.com/29655689/84594836-59e1a700-ae87-11ea-8151-2fae39d938b1.png)

**Comment by githubaby** [comment]
直接发布虽然可以自动跳转到预览
但是个人作品列表里直接点就是如上图

**Comment by iRuxu** [comment]
已解决，作者自己可以预览了
