### ISSUE TITLE
在快捷查看里复制云端宏

### ISSUE THREAD

**Issue by chenxuyi8023** [JX3BOX/jx3box.github.io#4]
目前复制功能可在详情页里面复制，而快捷查看宏只能复制宏命令而无法复制云端宏名称
![QQ截图20200615130109](https://user-images.githubusercontent.com/62126634/84619787-bd5fe900-af08-11ea-9c31-62e9759d9c1b.jpg)
![QQ截图20200615130052](https://user-images.githubusercontent.com/62126634/84619808-cb156e80-af08-11ea-98b7-e015f4b0b4a7.jpg)

**Comment by iRuxu** [comment]
是故意这样设置，这个只是预览一下大体内容
