### ISSUE TITLE
图标显示的功能不一致

### ISSUE THREAD

**Issue by chenxuyi8023** [JX3BOX/jx3box.github.io#5]
在教程发布时https://www.jx3box.com/post/?pt=tool
编辑器剑三的图标为：插入剑三资源
![教程](https://user-images.githubusercontent.com/62126634/84620540-e08b9800-af0a-11ea-8ace-52390400cb8a.jpg)
但是其他栏目，如职业，副本发布时https://v2.jx3box.com/dashboard/publish/#/fb
编辑器剑三的图标为：插入剑三图标，导致无法插入剑三资源
![职业](https://user-images.githubusercontent.com/62126634/84620656-26486080-af0b-11ea-81b2-e0fd31a413b0.jpg)

**Comment by iRuxu** [comment]
后续其他插入会修改
